name: appkitpdf
description: "App Kit PDF - Complete PDF Toolkit"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  syncfusion_flutter_pdf: ^28.1.33
  pdfx: ^2.7.0
  pdf: ^3.11.1
  file_picker: ^8.1.4
  path_provider: ^2.1.4
  image: ^4.2.0
  google_mlkit_text_recognition: ^0.14.0
  archive: ^3.6.1
  share_plus: ^10.1.2
  open_filex: ^4.5.0
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/c.png"
